### ISSUE TITLE
presenter

### ISSUE THREAD

**Issue by Yasamin-Nourijelyani** [CSC207-UofT/course-project-csc207gang-amazondevelopers#131]
add presenters and use case interfaces

**Comment by Yasamin-Nourijelyani** [comment]
feed, search, welcome page, 
for the making post, the user is given prompts to input information. Does that need to be seperated into contoller and presenter? And wouldnt that create unnecessary calls of the presenter to the controller

**Comment by Umayrah902** [comment]
Presenters have been made as needed.
