### ISSUE TITLE
Product adding and removing

### ISSUE THREAD

**Issue by Yasamin-Nourijelyani** [CSC207-UofT/course-project-csc207gang-amazondevelopers#33]
- connecting product to serialization
- changing quantity of product
- adding like, comments, etc to product (not need for post anymore)

**Comment by Yasamin-Nourijelyani** [comment]
testing

**Comment by samgunn03** [comment]
Assign a created product to a user.

**Comment by Yasamin-Nourijelyani** [comment]
the products dont ever get saved to a specific user, they are just created and nothing else happens
